In [1]:
import torch
import math

Create a 1D tensor from the Python list [1, 2, 3, 4, 5] and print its shape. Then, reshape it to a 2D tensor of shape (5, 1) and print the new tensor.

In [2]:
a = torch.tensor([1, 2, 3, 4, 5])
print(a)
print(a.shape)

a_reshaped = a.view(5, 1)
print( a_reshaped)

tensor([1, 2, 3, 4, 5])
torch.Size([5])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])


Write a Python program that creates a tensor of shape (3, 3) filled with random values between 0 and 1 using PyTorch. Print the tensor.

In [4]:
b = torch.rand(3, 3)
print(b)

tensor([[0.3663, 0.5134, 0.1045],
        [0.4011, 0.4428, 0.1436],
        [0.2269, 0.8657, 0.7407]])


Create a tensor filled with zeros of shape (2, 4) using PyTorch. Then, slice this tensor to get the first row and print it.

In [6]:
a = torch.zeros(2, 4)
print(a)
print(a[0])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([0., 0., 0., 0.])


Using PyTorch, create two 2D tensors A of shape (3, 2) and B of shape (2, 3). Perform matrix multiplication between A and B and print the result.

In [5]:
a = torch.rand(3, 2)
b = torch.rand(2, 3)
print(a)
print(b)
print(torch.matmul(a, b))

tensor([[0.6439, 0.4531],
        [0.5917, 0.8490],
        [0.9903, 0.6841]])
tensor([[0.8908, 0.7200, 0.3515],
        [0.3119, 0.7994, 0.8293]])
tensor([[0.7149, 0.8258, 0.6021],
        [0.7919, 1.1047, 0.9120],
        [1.0955, 1.2598, 0.9153]])


Write a Python function using PyTorch to compute the element-wise addition and multiplication of two tensors. Create two random tensors of the same shape and perform these operations.

In [13]:
a = torch.rand(2, 2) * 5
b = torch.rand(2, 2) + 11
c = a * b
d = a + b

print(c)
print(d)

tensor([[ 8.4535, 23.6388],
        [45.5579, 25.7082]])
tensor([[11.8396, 13.3743],
        [15.2195, 13.5988]])


Write a Python program that creates a 2D tensor of shape (3, 3) filled with ones. Then, use PyTorch to concatenate this tensor along the columns with another tensor of shape (3, 2) filled with random values.

In [16]:
ones = torch.ones(3, 3)
rand = torch.rand(3, 2)
c = torch.concat((ones, rand), dim=1)
print(c)

tensor([[1.0000, 1.0000, 1.0000, 0.2425, 0.7770],
        [1.0000, 1.0000, 1.0000, 0.3039, 0.3952],
        [1.0000, 1.0000, 1.0000, 0.9023, 0.1257]])


Create a tensor of shape (4, 4) filled with random integers between 1 and 10 using PyTorch. Then, reshape the tensor to (2, 8) and print both the original and reshaped tensors.

In [17]:
a = torch.randint(1, 11, (4, 4))
reshaped = a.view(2, 8)
print(a)
print(reshaped)

tensor([[10,  6,  8,  3],
        [ 5,  7, 10, 10],
        [ 2,  5,  3,  4],
        [ 4,  1,  2,  9]])
tensor([[10,  6,  8,  3,  5,  7, 10, 10],
        [ 2,  5,  3,  4,  4,  1,  2,  9]])
